language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
branches:
  except:
    - master
    - developer
services: redis-server
before_install:
  - travis_retry composer self-update
install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --verbose --coverage-text

matrix:
  allow_failures:
    - php: 5.4
    - php: hhvm
    - php: 7.0
  fast_finish: true
